// export const shoes = [
//   {
//     id: 1,
//     category: "Sneakers",
//     name: "AirMax Pro",
//     shoeImg: "https://unsplash.com/photos/q8AfPHM3duE",
//     price: 120,
//     oldPrice: 150,
//     description: "Lightweight running shoes with maximum cushioning.",
//     soldout: false,
//   },
//   {
//     id: 2,
//     category: "Boots",
//     name: "Trail Blazer",
//     shoeImg:
//       "https://images.unsplash.com/photo-1745576899457-1cbbab8ebdb9?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//     price: 180,
//     oldPrice: 200,
//     description: "Rugged boots for all-weather adventures.",
//     soldout: false,
//   },
//   {
//     id: 3,
//     category: "Sandals",
//     name: "Beach Breeze",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sandals,3",
//     price: 45,
//     oldPrice: 60,
//     description: "Open-toe comfort for summer strolls.",
//     soldout: true,
//   },
//   {
//     id: 4,
//     category: "Running",
//     name: "Speed Runner X",
//     shoeImg: "https://source.unsplash.com/random/400x400/?running-shoes,4",
//     price: 130,
//     oldPrice: 160,
//     description: "Engineered for peak athletic performance.",
//     soldout: false,
//   },
//   {
//     id: 5,
//     category: "Sneakers",
//     name: "Urban Walk",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sneakers,5",
//     price: 90,
//     oldPrice: 120,
//     description: "Sleek everyday sneakers for the city life.",
//     soldout: true,
//   },
//   {
//     id: 6,
//     category: "Boots",
//     name: "Everest Trek",
//     shoeImg: "https://source.unsplash.com/random/400x400/?boots,hiking,6",
//     price: 210,
//     oldPrice: 250,
//     description: "High-performance boots for mountain trails.",
//     soldout: false,
//   },
//   {
//     id: 7,
//     category: "Formal",
//     name: "Gentleman Classic",
//     shoeImg: "https://source.unsplash.com/random/400x400/?formal-shoes,7",
//     price: 140,
//     oldPrice: 170,
//     description: "Elegant formal shoes for special occasions.",
//     soldout: false,
//   },
//   {
//     id: 8,
//     category: "Loafers",
//     name: "Easy Slip",
//     shoeImg: "https://source.unsplash.com/random/400x400/?loafers,8",
//     price: 85,
//     oldPrice: 110,
//     description: "Casual slip-ons for effortless style.",
//     soldout: false,
//   },
//   {
//     id: 9,
//     category: "Sandals",
//     name: "Ocean Drift",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sandals,9",
//     price: 50,
//     oldPrice: 65,
//     description: "Water-resistant sandals perfect for beach days.",
//     soldout: false,
//   },
//   {
//     id: 10,
//     category: "Sneakers",
//     name: "Neon Pulse",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sneakers,10",
//     price: 110,
//     oldPrice: 140,
//     description: "Vibrant sneakers that energize your steps.",
//     soldout: true,
//   },
//   {
//     id: 11,
//     category: "Running",
//     name: "Flash Runner",
//     shoeImg: "https://source.unsplash.com/random/400x400/?running-shoes,11",
//     price: 125,
//     oldPrice: 155,
//     description: "Ultra-light shoes built for marathon runners.",
//     soldout: false,
//   },
//   {
//     id: 12,
//     category: "Formal",
//     name: "Executive Edge",
//     shoeImg: "https://source.unsplash.com/random/400x400/?formal-shoes,12",
//     price: 150,
//     oldPrice: 180,
//     description: "Premium leather shoes for boardroom success.",
//     soldout: false,
//   },
//   {
//     id: 13,
//     category: "Loafers",
//     name: "Weekend Vibe",
//     shoeImg: "https://source.unsplash.com/random/400x400/?loafers,13",
//     price: 70,
//     oldPrice: 95,
//     description: "Stylish loafers for relaxed weekends.",
//     soldout: false,
//   },
//   {
//     id: 14,
//     category: "Boots",
//     name: "Ranger Tough",
//     shoeImg: "https://source.unsplash.com/random/400x400/?boots,14",
//     price: 190,
//     oldPrice: 220,
//     description: "Built tough for the harshest environments.",
//     soldout: true,
//   },
//   {
//     id: 15,
//     category: "Sneakers",
//     name: "Galaxy Step",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sneakers,15",
//     price: 95,
//     oldPrice: 130,
//     description: "Futuristic design and ultimate comfort.",
//     soldout: false,
//   },
//   {
//     id: 16,
//     category: "Running",
//     name: "Pace Master",
//     shoeImg: "https://source.unsplash.com/random/400x400/?running-shoes,16",
//     price: 135,
//     oldPrice: 165,
//     description: "Perfect balance of speed and endurance.",
//     soldout: true,
//   },
//   {
//     id: 17,
//     category: "Sandals",
//     name: "Sunset Slides",
//     shoeImg: "https://source.unsplash.com/random/400x400/?sandals,17",
//     price: 40,
//     oldPrice: 55,
//     description: "Comfortable slides for sunny days.",
//     soldout: false,
//   },
//   {
//     id: 18,
//     category: "Formal",
//     name: "Velvet Touch",
//     shoeImg: "https://source.unsplash.com/random/400x400/?formal-shoes,18",
//     price: 160,
//     oldPrice: 190,
//     description: "Sophisticated and smooth to the touch.",
//     soldout: false,
//   },
//   {
//     id: 19,
//     category: "Loafers",
//     name: "City Cruiser",
//     shoeImg: "https://source.unsplash.com/random/400x400/?loafers,19",
//     price: 95,
//     oldPrice: 120,
//     description: "Effortless fashion for urban living.",
//     soldout: true,
//   },
//   {
//     id: 20,
//     category: "Boots",
//     name: "Winter Warrior",
//     shoeImg: "https://source.unsplash.com/random/400x400/?winter-boots,20",
//     price: 220,
//     oldPrice: 260,
//     description: "Stay warm and stylish through winter storms.",
//     soldout: false,
//   },
// ];

export const shoes = [
  {
    id: 1,
    category: "Sneakers",
    name: "Air Zoom Pegasus",
    shoeImg: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    price: 120,
    oldPrice: 150,
    description: "Lightweight and fast sneakers perfect for everyday running.",
    soldout: false,
  },
  {
    id: 2,
    category: "Boots",
    name: "Mountain Boots",
    shoeImg: "https://images.unsplash.com/photo-1600180758890-6b94521b1963",
    price: 180,
    oldPrice: 220,
    description: "Durable boots built for extreme mountain adventures.",
    soldout: false,
  },
  {
    id: 3,
    category: "Casual",
    name: "Canvas Classics",
    shoeImg: "https://images.unsplash.com/photo-1618354691908-7611c812611e",
    price: 70,
    oldPrice: 100,
    description: "Timeless canvas sneakers for a relaxed, everyday look.",
    soldout: false,
  },
  {
    id: 4,
    category: "Formal",
    name: "Oxford Elegance",
    shoeImg: "https://images.unsplash.com/photo-1586943352121-73c3a0409ec5",
    price: 200,
    oldPrice: 250,
    description:
      "Premium leather shoes designed for business and formal events.",
    soldout: false,
  },
  {
    id: 5,
    category: "Sport",
    name: "Trail Runner",
    shoeImg: "https://images.unsplash.com/photo-1585386959984-a4155228c1f7",
    price: 150,
    oldPrice: 180,
    description:
      "Rugged shoes made for wild trail running and outdoor workouts.",
    soldout: false,
  },
];
